### ISSUE TITLE
AnalyticsStatus - localized date

### ISSUE THREAD

**Issue by mathieuchateau** [acasilla/SPFarmInfo#5]
inside function AnalyticsStatus.
de.Value is a string, with local date format.

Example with ambigous date:
03/11/2023 13:00:00

In English format it would mean 11 of March
In French, format, it means 11 of November.

System.DateTime]::TryParse is not crashing, as we are before 13, so month is possible.

So it generated false alert that things did not run since more than 3 days, which is wrong.

I switched to this way, using a local Get-Date which will use current culture:

```
                        try
			{
				get-date $de.Value
			}
			catch
			{
                        	$dlast = Get-Date
			}


```
 if ($de.Key -match "Last successful start time")
                    {
                        $dlast = Get-Date
                        try
			{
				get-date $de.Value
			}
			catch
			{
                        	$dlast = Get-Date
			}
                        $dNow = Get-Date
                        $daysSinceLastSuccess = $dNow.DayOfYear - $dLast.DayOfYear
                        if ($daysSinceLastSuccess -gt 3)
                        {
                        	$AnalyticsEntryFindings.Severity = [SPDiagnostics.Severity]::Warning
                                $AnalyticsEntryFindings.WarningMessage += "Warning: More than three days since last successful run"
                                $script:serviceDegraded = $true                        
                        }
                    }
```

**Comment by StuartP-MSFT** [comment]
@mathieuchateau , This one we had to change from using Get-Date alone because of problems when certain customers used ShortDate format set to "05-Apr-17" here in US.  The Get-Date $de.Value will transpose the month and year incorrectly in US when converting the detail's last run date, if the OS is using a shortdate like above. The details date value is ALWAYS in the format of MM/DD/YYY HH:MM:SS despite the regional settings of the OS, SP, SQL, etc,. 

To address both of these issues, (short date format changes and other culture format differences) I believe calling TryParse with InvariantCulture in both places will suffice.

I did a quick test on this by changing regional formats in my lab to DD/MM/YYYY and passing in this test code:

```
$detail = "11/9/2023 12:00:01 AM"
$dateLast = Get-Date
$dateNow = Get-Date
[System.DateTime]::TryParse($detail, [System.Globalization.CultureInfo]::InvariantCulture,[System.Globalization.DateTimeStyles]::None, [ref]$dateLast)
[System.DateTime]::TryParse($dateNow, [System.Globalization.CultureInfo]::InvariantCulture,[System.Globalization.DateTimeStyles]::None, [ref]$dateNow)


$dateLast
$dateLast.ToString()
$dateNow
$dateNow.ToString()

```
This returned:
Thursday, 9 November 2023 00:00:01
09/11/2023 00:00:01
Thursday, 9 November 2023 20:26:12
09/11/2023 20:26:12

Could you let me know if this works for you?

```
 if ($details.Key -match "Last successful start time")
                    {
                        # Just passing in a current DateTime for TryParse method requirement
                        $dateLast = Get-Date

                        # Use ParseDateTime. This is required to support ShortDate formats that some customers use
                        # We have to do this because the details value is ALWAYS in the format of MM/DD/YYYY HH:MM:SS
                        if([System.DateTime]::TryParse($details.Value, [System.Globalization.CultureInfo]::InvariantCulture,[System.Globalization.DateTimeStyles]::None, [ref]$dateLast))
                        {
                            $dateNow = Get-Date

                            # While this seems redundant, when using alternate date formast from MM/DD/YYYY  on OS, this is required to ensure both dateLast and dateNow follow the same format
                            if([System.DateTime]::TryParse($dateNow.Value, [System.Globalization.CultureInfo]::InvariantCulture,[System.Globalization.DateTimeStyles]::None, [ref]$dateNow))
                            {
                                # Use DateTime subtraction to get a timespan. Previous method used DayOfYear which isn't a valid comparison between the change of years
                                $daysSinceLastSuccess = $dateNow - $dateLast

                                if ($daysSinceLastSuccess.Days -gt 3)
                                {
                                    $AnalyticsEntryFindings.Severity = [SPDiagnostics.Severity]::Warning
                                    $AnalyticsEntryFindings.WarningMessage += "Warning: More than three days since last successful run"
                                    $script:serviceDegraded = $true                        
                                }
                            }
                        }
                    }
```
Apologies on changing the names here, I'm trying to minimize the overly abbreviated variable names so fixing them when I come across them.

**Comment by StuartP-MSFT** [comment]
Closing issue
